project:
    
  type: website
  output-dir: docs 
  title: "Shahram Dehghan jabarabadi | Postdoc & Expert in Econometrics and Textual Analysis"
  resources:
    - "googlea001f7a2c08a32a0.html"
    - "robots.txt"
    - "sitemap.xml" 


website:
  
  site-url: "https://shahram-dehghan-j.github.io"
  
  navbar:
    title: false   # hides the title from the navbar
    left:
      - text: 'Home'
        href: index.qmd
      - text: 'Interests'
        href: interests.qmd
      - text: 'Educations'
        href: educations.qmd
      - text: 'Publications'
        href: publications.qmd
      - text: 'Teaching'
        href: teaches.qmd
      - text: 'Awards'
        href: awards.qmd
      - text: 'CODES'
        menu:
          - text: "Data"
            href: dataPage.qmd
          - text: "Python"
            href: pythonPage.qmd
          - text: "R"
            href: rPage.qmd
          - text: "LaTeX"
            href: latexPage.qmd
    
    right:
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=W_Qsf4MAAAAJ&hl=it&oi=ao
      - text: '<img src="/ORCID_iD_icon.svg" alt="ORCID" style="height:20px; vertical-align:middle;">'
        href: https://orcid.org/0009-0008-4627-7554
      - icon: linkedin
        href: https://www.linkedin.com/in/shahram-dehghan-jabarabadi
      - icon: envelope-at
        href: mailto:shahram.deghan.j@icloud.com
   
  sidebar:
    style: "docked"
    contents:
        - text: "<img src='/websiteIMG.jpg' style='border-radius:50%/50%;width:220px;height:250px;'>"
        - text: "<strong>Ph.D.</strong>"
        - text: "<strong>Shahram Dehghan Jabarabadi</strong>"
        - text: "Postdoctoral Research Fellow"
        - text: "University of Padua <a href='https://www.economia.unipd.it/'>(dSEA)</a>"
        - text: "<i class='bi bi-book me-2'></i>Research Interests:<br><br><span class='ms-5'>Econometrics</span><br><span class='ms-5'>Textual Analysis</span><br><span class='ms-5'>Risk Management</span><br><span class='ms-5'>TimeSeries</span><br><span class='ms-5'>Volatility Analysis</span><br><span class='ms-5'>Python/R</span><br><br>"
        - text: "<i class='bi bi-mortarboard me-2'></i> <a href='https://scholar.google.com/citations?user=W_Qsf4MAAAAJ&hl=it&oi=ao'>Google Scholar</a>"
        - text: "<img src='/ORCID_iD_icon.svg' alt='ORCID' style='height:20px; vertical-align:middle; margin-right:6px;'> <a href='https://orcid.org/0009-0008-4627-7554'>ORCID</a>"
        - text: "<i class='bi bi-envelope me-2'></i> <a href='mailto:shahram.deghan.j@icloud.com'>shahram.dehghan.j</a>"


  page-footer:
    left: 
      - text: 'ðŸ‡®ðŸ‡· - ðŸ‡®ðŸ‡¹ <br> Copyright Â© 2024. <a href="https://www.wipo.int/copyright/en/" target="_blank">Legal Info</a>'
    right:
      - text: "<strong>Â© <script>document.write(new Date().getFullYear());</script> Shahram Dehghan Jabarabadi</strong>"
    center: 
      - text: "<i class='bi bi-geo-alt me-2'></i> Padua, Italy"

format:
  html:
    theme: journal
    canonical-url: true
    css: styles.css
    html-meta:
      google-site-verification: "googlea001f7a2c08a32a0"
      description: "Personal academic website of Shahram Dehghan Jabarabadi, Postdoctoral Research Fellow at the University of Padua. Specializing in Econometrics, Textual Analysis, and Quantitative Finance with expertise in Time Series, Risk Management (VaR/ES/GARCH), and NLP (Sentiment/Topic Modeling). Research focuses on volatility, ESG indicators, and text-based analysis of economic systems."
      keywords: "Shahram Dehghan Jabarabadi, Shahram Dehghan, Shahram, Dehghan, Jabarabadi, Economics, Econometrics, Textual Analysis, Quantitative Finance, Time Series Analysis, Risk Management, Natural Language Processing, NLP, Statistical Methods, GARCH, VaR, ES, ESG Integration, Volatility Analysis, Python, R,  University of Salerno, University of Padua, Postdoctoral Fellow, Research, Ph.D., Docotrate, Dr."
    include-in-header:
      - text: |
          <!-- Font Awesome -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
          <!-- Academicons -->
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons/css/academicons.min.css">


